/* sound_data.h - Generated WAV file data */
#ifndef SOUND_DATA_H
#define SOUND_DATA_H

#include "stdint.h"

/* WAV file size */
#define WAV_SIZE 44100

/* WAV file data */
const uint8_t wav_data[WAV_SIZE] = {
    /* RIFF header */
    'R', 'I', 'F', 'F',
    0x44, 0xAC, 0x00, 0x00,  /* File size - 8 (example) */
    'W', 'A', 'V', 'E',
    
    /* Format chunk */
    'f', 'm', 't', ' ',
    0x10, 0x00, 0x00, 0x00,  /* Format chunk size (16) */
    0x01, 0x00,              /* Audio format (1 = PCM) */
    0x02, 0x00,              /* Number of channels (2 = stereo) */
    0x44, 0xAC, 0x00, 0x00,  /* Sample rate (44.1kHz) */
    0x10, 0xB1, 0x02, 0x00,  /* Byte rate (44.1kHz * 2ch * 16bit / 8) */
    0x04, 0x00,              /* Block align (2ch * 16bit / 8) */
    0x10, 0x00,              /* Bits per sample (16) */
    
    /* Data chunk */
    'd', 'a', 't', 'a',
    0x20, 0xAC, 0x00, 0x00,  /* Data chunk size (example) */

    /* This is where the actual PCM audio data would go */
    /* It would be generated by the wav2header.sh script */
    /* For brevity, we're not including thousands of bytes here */
    /* A real file would have actual PCM data here */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* ... more data ... */
};

#endif /* SOUND_DATA_H */